#
#Author: James Anthony Ortiz
#Description: Makefile for Section 3 Programs:
#

#enum class example
traffic_light: enum_class.cpp
	g++ -std=c++11 -Wall -Wextra enum_class.cpp -o enum_class
#vector class example
vector_class: vector_class.cpp
	g++ -std=c++11 -Wall -Wextra vector_class.cpp -o vector_class
#vector struct example
vector_struct: vector_struct.cpp
	g++ -std=c++11 -Wall -Wextra vector_struct.cpp -o vector_struct

#static_assert example
static_assert:  static_assert.cpp
	g++ -std=c++11 -Wall -Wextra static_assert.cpp -o static_assert

clean:
	rm -rf *.o
